application: fuzzy-bee
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
      
- url: /css
  static_dir: static/css

- url: /.*
  script: bee.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
